// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/psych-model/biz/adaptor"
	"github.com/xh-polaris/psych-model/biz/adaptor/controller"
	"github.com/xh-polaris/psych-model/biz/application/service"
	"github.com/xh-polaris/psych-model/biz/infrastructure/config"
	"github.com/xh-polaris/psych-model/biz/infrastructure/mapper/app"
	"github.com/xh-polaris/psych-model/biz/infrastructure/mapper/model"
)

// Injectors from wire.go:

func NewProvider() (*adaptor.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mongoMapper := model.NewMongoMapper(configConfig)
	appMongoMapper := app.NewMongoMapper(configConfig)
	unitAppConfigService := &service.UnitAppConfigService{
		ModelMapper: mongoMapper,
		AppMapper:   appMongoMapper,
	}
	unitAppConfigController := &controller.UnitAppConfigController{
		UnitAppConfigService: unitAppConfigService,
	}
	appService := &service.AppService{
		AppMapper:   appMongoMapper,
		ModelMapper: mongoMapper,
	}
	appController := &controller.AppController{
		AppService: appService,
	}
	server := &adaptor.Server{
		IUnitAppConfigController: unitAppConfigController,
		IAppController:           appController,
	}
	return server, nil
}
